#!/bin/bash

updatecmd="gitchangelog"
echo "$0 will update the ChangeLog file. It use ${updatecmd}."
if ! command -v ${updatecmd} &>/dev/null ; then
	echo "${updatecmd} could not be found"
	exit
fi

gitchangelog > ChangeLog
echo "For mode details, run 'git log'." >> ChangeLog
