#!/usr/bin/env bash

# FVWM-Crystal helper script that check for mount changes
# Usage: Exec exec $[FVWM_SYSTEMDIR]/scripts/DesktopCheckMounts <delay [s]> <optional PID>

#source "${FVWM_SYSTEMDIR}"/scripts/DesktopCheckParent

# be sure no old instance are runninng for the same fvwm parent or with no fvwm parent:
#PFExec="search_parent_pid"
#ParentFvwm=$(${PFExec} $$)
#for i in $(pgrep -f DesktopCheckMounts) ; do
#	if [[ $$ -ne ${i} ]] ; then
#		if [[ ${ParentFvwm} -eq $(${PFExec} ${i}) ]] || [[ "nofvwmp" == "$(${PFExec} ${i})" ]] ; then
#			kill ${i}
#    		fi
#	fi
#done

# tell the kernal to handle parent death into a robust way
#setpriv --pdeathsig TERM

# write the PID to a file
echo "$$" > "${FVWM_USERDIR}/tmp/DeCheckMounts_${DISPLAY}".pid

# delete PID file at exit
cleanup() {
	echo cleanup "$0"
	exit 0
}
trap "cleanup" HUP TERM

send_to_fvwm() {
	if [ "${FVWM_IS_FVWM3}" = "1" ]; then
		FvwmPrompt "$@"
	else
		FvwmCommand "$@"
	fi
}
send_to_fvwm InfoStoreAdd DeCheckMounts_"${DISPLAY}" "$$"

# We only want the partitions the user have access to => use their path
MountedP=$(mount|cut -d" " -f3)
check_access() {
	AccTo=""
	for part in $1 ; do
		if [ "$(ls "${part}" 2>/dev/null)" ] ; then
			AccTo="${AccTo} $part"
		fi
	done
	echo "${AccTo}"
}
MountedP="$(check_access "${MountedP}")"

# the main loop
while :
do
#	sleep "$1"
	# read -t is not posix => keep bash. or revert to sleep and use sh
	read -t "$1" -s -N 1 nop
	# fvwm is started by exec; be sure it is running
#	pidof fvwm 1>/dev/null || pidof fvwm3 1>/dev/null || cleanup

	NMountedP=$(mount|cut -d" " -f3)
	NMountedP="$(check_access "${NMountedP}")"
	if [[ "$NMountedP" != "$MountedP" ]]; then
		MountedP="${NMountedP}"
		send_to_fvwm LoadDesktopIcons
	fi
done
