#!/usr/bin/env sh

# FVWM-Crystal helper script that check for mount changes
# Usage: Exec exec $[FVWM_SYSTEMDIR]/scripts/DesktopCheckMounts <delay [s]>
# or:	 ExecScript DesktopCheckMounts <delay [s]>

# cleanup can be done after fvwm exits, be sure these vars are setup:
FVWM_USERDIR="${FVWM_USERDIR}"
DISPLAY="${DISPLAY}"
# See ExecScript in components/Standard:
PIDFile="${FVWM_USERDIR}/tmp/DeCheckMounts_${DISPLAY}.pid"
cleanup() {
	rm -f "${PIDFile}"
	echo "cleanup $$"
	exit 0
}
trap "cleanup" HUP TERM

# test OK: echo "FVWMMFL_SOCKET_PATH = ${FVWMMFL_SOCKET_PATH}" > ${FVWM_USERDIR}/tmp/fvwm_mfl_sock

# kill old instance
if [ -f "${PIDFile}" ]; then
	kill -9 "$(cat "${PIDFile}")" 2>/dev/null
fi
# write PID file
mkdir -p "${FVWM_USERDIR}"/tmp
echo "$$" > "${PIDFile}"

send_to_fvwm() {
	if [ "${FVWM_IS_FVWM3}" = "1" ]; then
		FvwmPrompt "$@"
	else
		FvwmCommand "$@"
	fi
}

# We only want the partitions the user have access to => use their path
MountedP=$(mount|cut -d" " -f3)
check_access() {
	AccTo=""
	for part in $1 ; do
		if [ "$(ls "${part}" 2>/dev/null)" ] ; then
			AccTo="${AccTo} $part"
		fi
	done
	echo "${AccTo}"
}
MountedP="$(check_access "${MountedP}")"

# the main loop
while :
do
	sleep "$1"

	NMountedP=$(mount|cut -d" " -f3)
	NMountedP="$(check_access "${NMountedP}")"
	if [ "$NMountedP" != "$MountedP" ]; then
		MountedP="${NMountedP}"
		send_to_fvwm LoadDesktopIcons
	fi
done
