#!/bin/bash

# FVWM-Crystal: wraapper for automatic Fullscreen
# Generate the Window-AutoFS function from the user preferences.
# Written by: Dominique Michel 2015-2022
# <dominique_libre@users.sourceforge.net>

echo "DestroyFunc Window-AutoFS"
echo "AddToFunc Window-AutoFS"
while read myline
do 	if [ "${myline}" != "" ]
	then
		echo "+ I WindowId \$\$[0] (${myline}, !Transient) Fullscreen"
	fi
done < ${FVWM_USERDIR}/preferences/FullScreenApps|grep -v -e '#'
