#!/usr/bin/env bash
# On laptop, suspend hybrid from components/functions/Exit

# cleanup can be done after fvwm exits, be sure these vars are setup:
FVWM_USERDIR="${FVWM_USERDIR}"
DISPLAY="${DISPLAY}"
# See ExecScript in components/Standard:
PIDFile="${FVWM_USERDIR}/tmp/ScreenLidSuspend_${DISPLAY}.pid"
cleanup() {
	rm -f "${PIDFile}"
	echo "cleanup $$"
	exit 0
}
trap "cleanup" HUP TERM

# kill old instance
if [ -f "${PIDFile}" ]; then
	kill -9 "$(cat "${PIDFile}")" 2>/dev/null
fi
# write PID file
mkdir -p "${FVWM_USERDIR}"/tmp
echo "$$" > "${PIDFile}"

if [[ $1 == *pm* ]] ; then
	PMV=pm
elif [[ $1 == *sysctl ]] ; then
	PMV=sys
elif [[ $1 == *loginctl ]] ; then
	PMV=log
fi

while :
do
	sleep 5
	grep -q closed /proc/acpi/button/lid/*/state
	if [ $? = 0 ]; then
		case "${PMV}" in
			pm)
				sudo "${PMV}"
				;;
			log)
				sudo "${PMV}" hybrid-sleep
				;;
			sys)
				sudo "${PMV}" hybrid-sleep -i
				;;
			*)
				exit 1
				;;
		esac
	fi
done
