#!/bin/bash
# On laptop, suspend hybrid from components/functions/Exit

lidsleeppm() {
	while :
	do
	    sleep 5
	    grep -q closed /proc/acpi/button/lid/*/state
	    if [ $? = 0 ]; then
		if [[ $2 == pm ]]; then
		    sudo $1
		fi
		if [[ $2 == log ]]; then
		    $1 hybrid-sleep
		fi
		if [[ $2 == sys ]]; then
		    $1 hybrid-sleep -i
		fi
	    fi
	done
}

if [[ $1 == *pm* ]] ; then
	PMV=pm
elif [[ $1 == *sysctl ]] ; then
	PMV=sys
elif [[ $1 == *loginctl ]] ; then
	PMV=log
fi

lidsleeppm $1 "${PMV}"
